#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd)"
source "${SCRIPT_DIR}/env.bash"

mkdir -p "${SOURCE_DIR}"
mkdir -p "${INSTALL_DIR}"

apt update -y

apt install -y \
    build-essential \
    debhelper \
    pbuilder \
    devscripts \
    wget

RUBY_SOURCE_VERSION_PREFIX="$(echo "$RUBY_SOURCE_VERSION" | sed -E 's/\.[0-9]+$//')"
wget -O- \
    "https://cache.ruby-lang.org/pub/ruby/${RUBY_SOURCE_VERSION_PREFIX}/ruby-${RUBY_SOURCE_VERSION}.tar.gz" \
    | tar xzf - -C "${SOURCE_DIR}" --strip-components 1

# Install build dependencies
apt install -y \
    bison \
    coreutils \
    debhelper-compat \
    file \
    libffi-dev \
    libgdbm-compat-dev \
    libgdbm-dev \
    libgmp-dev \
    libncurses-dev \
    libedit-dev \
    libssl-dev \
    libyaml-dev \
    libjemalloc-dev \
    netbase \
    openssl \
    pkg-config \
    procps \
    systemtap-sdt-dev \
    tzdata \
    zlib1g-dev

DEB_BUILD_GNU_TYPE="$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)"

cd "${SOURCE_DIR}"

./configure \
    "--prefix=${INSTALL_DIR}/usr" \
    --enable-multiarch \
    "--program-suffix=${SUFFIX}" \
    "--with-soname=ruby${SUFFIX}" \
    --enable-shared \
    --disable-rpath \
    --with-sitedir=/usr/local/lib/site_ruby \
    "--with-sitearchdir=/usr/local/lib/${DEB_BUILD_GNU_TYPE}/site_ruby" \
    --runstatedir=/var/run \
    "--localstatedir=${INSTALL_DIR}/var" \
    --sysconfdir=/etc \
    --enable-ipv6 \
    --with-jemalloc \
    --with-dbm-type=gdbm_compat \
    --with-compress-debug-sections=no \
    "AS=${DEB_BUILD_GNU_TYPE}-as" \
    "CC=${DEB_BUILD_GNU_TYPE}-gcc" \
    "CXX=${DEB_BUILD_GNU_TYPE}-g++" \
    "LD=${DEB_BUILD_GNU_TYPE}-ld" \
    EGREP='/bin/grep -E' \
    GREP='/bin/grep' \
    MAKEDIRS='/bin/mkdir -p' \
    MKDIR_P='/bin/mkdir -p' \
    SHELL='/bin/sh'

make install
