#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/env.bash"

DEB_HOST_ARCH="$(dpkg-architecture -qDEB_HOST_ARCH)"

apt install -y \
    rsync

cd "${INSTALL_DIR}"

mkdir -p "${INSTALL_DIR}/ruby-jemalloc-dev/DEBIAN"
rsync --recursive --relative --links \
    usr/bin \
    usr/share/man \
    usr/include \
    usr/lib/*/*.so.* \
    usr/lib/*/pkgconfig \
    usr/lib/*/ruby \
    usr/lib/ruby \
    "${INSTALL_DIR}/ruby-jemalloc-dev/"

for bin_path in "${INSTALL_DIR}/ruby-jemalloc-dev/usr/bin"/*; do
    ln -sf "$(basename "${bin_path}")" "${bin_path%%-jemalloc}"
done

m4 "-D__ARCH__=${DEB_HOST_ARCH}" \
    "${ASSETS_DIR}/ruby-jemalloc-dev/DEBIAN/control.m4" \
    > "${INSTALL_DIR}/ruby-jemalloc-dev/DEBIAN/control"

dpkg-deb --build "${INSTALL_DIR}/ruby-jemalloc-dev/" .
