#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/env.bash"

TARGET_ARCH="${TARGET_ARCH:-"$(dpkg-architecture -qDEB_HOST_ARCH)"}"

apt install -y \
    rsync

cd "${INSTALL_DIR}"

mkdir -p "${INSTALL_DIR}/ruby-jemalloc-dev/DEBIAN"
rsync --recursive --relative --links \
    usr/bin \
    usr/local/bin \
    usr/share/man \
    usr/include \
    usr/lib/*/*.so.* \
    usr/lib/*/pkgconfig \
    usr/lib/*/ruby \
    usr/lib/ruby \
    "${INSTALL_DIR}/ruby-jemalloc-dev/"

m4 "-D__ARCH__=${TARGET_ARCH}" \
    "${SCRIPT_DIR}/../ruby-jemalloc-dev/DEBIAN/control.m4" \
    > "${INSTALL_DIR}/ruby-jemalloc-dev/DEBIAN/control"

# Ubuntu use zstd by default and Debian failed to unpack zstd archive.
dpkg-deb -Zgzip --build "${INSTALL_DIR}/ruby-jemalloc-dev/" .
