name: Deploy for x86_64 / Debian bullseye

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: 'debian:bullseye'

        steps:
            -   uses: actions/checkout@v3

            -   name: Build Ruby
                run: env TRACE=true ./debian/scripts/build-source

            -   name: Build deb
                run: env TRACE=true ./debian/scripts/build-deb

            -   name: Install testing
                run: apt install -y ./install/*.deb

            -   name: Show Ruby version
                run: ruby --version && /usr/bin/ruby-jemalloc --version

            -   name: Release
                uses: softprops/action-gh-release@v1
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    files: |
                        ./install/*.deb
