name: Build and Deploy for x86_64 arch

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@v3

            -   name: Build Ruby
                run: sudo env TRACE=true ./scripts/build-source

            -   name: Build deb
                run: sudo env TRACE=true ./scripts/build-deb

            -   name: Release
                uses: softprops/action-gh-release@v1
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    files: |
                        install/*.deb
