name: Build and Deploy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@v3

            -   name: Build Ruby
                run: sudo env TRACE=true ./scripts/build-source

            -   name: Build deb
                run: sudo env TRACE=true ./scripts/build-deb
